# Generated by Django 5.1.6 on 2026-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DELETE_USER', 'Delete User'), ('ACTIVATE_USER', 'Activate User'), ('DEACTIVATE_USER', 'Deactivate User'), ('CHANGE_PASSWORD', 'Change Password'), ('CREATE_ROLE', 'Create Role'), ('UPDATE_ROLE', 'Update Role'), ('DELETE_ROLE', 'Delete Role'), ('CREATE_PERMISSION', 'Create Permission'), ('UPDATE_PERMISSION', 'Update Permission'), ('DELETE_PERMISSION', 'Delete Permission')], max_length=50),
        ),
    ]
