# Generated by Django 5.1.6

import django

from django.db import migrations, models


def migrate_legacy_data(apps, schema_editor):
    User = apps.get_model("users", "User")

    # ---------------------------------------------------------
    # 1. Copiar User.groups -> User.iam_groups
    # ---------------------------------------------------------
    for user in User.objects.all():
        old_groups = user.groups.all()

        for group in old_groups:
            user.iam_groups.add(group)

    # ---------------------------------------------------------
    # 2. Copiar User.role -> User.roles
    # ---------------------------------------------------------
    for user in User.objects.all():
        if user.role_id:
            user.roles.add(user.role_id)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_groups"),
    ]

    operations = [

        # -----------------------------------------------------
        # Role.organization
        # -----------------------------------------------------
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="users.organization",
            ),
        ),

        # -----------------------------------------------------
        # User.iam_groups
        # -----------------------------------------------------
        migrations.AddField(
            model_name="user",
            name="iam_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.group",
            ),
        ),

        # -----------------------------------------------------
        # User.organization
        # -----------------------------------------------------
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.organization",
            ),
        ),

        # -----------------------------------------------------
        # User.roles
        # -----------------------------------------------------
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="users.role",
            ),
        ),

        # -----------------------------------------------------
        # Role.description
        # -----------------------------------------------------
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=255,
            ),
        ),

        # -----------------------------------------------------
        # Role.name
        # -----------------------------------------------------
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                max_length=50,
            ),
        ),

        # -----------------------------------------------------
        # Role.permissions
        # -----------------------------------------------------
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="users.permission",
            ),
        ),

        # -----------------------------------------------------
        # Unique role per organization
        # -----------------------------------------------------
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_role_per_organization",
            ),
        ),

        # -----------------------------------------------------
        # MIGRAÇÃO DOS DADOS ANTIGOS
        # -----------------------------------------------------
        migrations.RunPython(
            migrate_legacy_data,
            migrations.RunPython.noop,
        ),

        # -----------------------------------------------------
        # Só agora removemos o campo antigo role
        # -----------------------------------------------------
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
