# Generated by Django 5.1.6 on 2026-08-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
