# Generated by Django 5.1.6 on 2026-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_mfa_enabled_user_mfa_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_last_used_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
