# Generated by Django 5.1.6 on 2026-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='requires_step_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='risk_level',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='usersession',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='step_up_required_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='step_up_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
